---
title: "Projects"
output: 
  html_document:
    toc: true
    toc_float: true
---
<br>

### 1. A Linear Regression Model of US Crime Rate Prediction 
[Project Webisite](https://github.com/JING-LYU/bm_final_project).
<br>
In this project, we aim to build regression models based on a set of demographic variables to estimate county-level crime rates. After an exploratory analysis of the variables on their distributions and correlations, we derived more meaningful variables by manipulating the existing ones, removed outlier values, and implemented several variable selection methods. Using the selected variables, we trained a linear regression model, elaborated on the model by adding several interactive terms, and did cross-validations. All 3 resulting models have achieved a good estimation of the training set. We selected the third model (adjusted R-square: 0.542, RMSE: 16.46, RMSPE: 11.90) as the final model, as it has the best prediction on testing set. Further studies can be done on correcting the dataset using external data sources, as well as using more sophisticated non-linear models.

<br>

### 2.Saving as a non-smoker? Exploring relationship between smoking and health insurance
[Project Webisite](https://wyshanw.github.io/final_project/).
<br>
We notice that a lot of smokers complain about their insurance charges. In fact, it is known that the health insurance companies stratify smokers and non-smokers and assign different insurance prices according to smoking status. 

Since health insurance is vital for people’s well-being, and the cost is the main reason that stops people from buying insurance, we are interested in exploring the relationship between smoking and health insurance. To be specific, our research topic can be divided into three research questions. We would like to investigate:

* If smokers tend to get insurance; 
* What type of insurance they prefer; 
* Factors that affect insurance purchasing and premiums. 

Another reason that limits access to insurance is lack of information. As such, mapping of health consulting centers, health insurance carriers locations, and medicaid provider location in NYC, along with their contact information and operation hours, are also provided for readers who need more information for insurance and health advice.
